# Generated by Django 3.2 on 2021-05-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albumes',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('artist_id', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=500)),
                ('tracks', models.CharField(max_length=500)),
                ('self', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('albums', models.CharField(max_length=500)),
                ('tracks', models.CharField(max_length=500)),
                ('self', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('album_id', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('duration', models.FloatField()),
                ('times_played', models.IntegerField()),
                ('artist', models.CharField(max_length=500)),
                ('album', models.CharField(max_length=500)),
                ('self', models.CharField(max_length=500)),
            ],
        ),
    ]
